/**
 *
 * $Id$
 */
package taller1.validation;

import taller1.TipoAtributo;

/**
 * A sample validator interface for {@link taller1.Atributo}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AtributoValidator {
	boolean validate();

	boolean validateName(String value);

	boolean validateType(TipoAtributo value);

	boolean validateNombre(String value);

	boolean validateTipo(TipoAtributo value);

	boolean validateValor(TipoAtributo value);

	boolean validateIsPrimary(boolean value);

	boolean validateIsTitle(boolean value);

	boolean validateIsRequired(boolean value);

	boolean validateIsVisibleInList(boolean value);
}
